language: node_js

matrix:
  include:
  - os: osx
    node_js: 8.1.3
    TEST_SCRIPT: coffeescript
  - os: osx
    node_js: 8.1.3
    TEST_SCRIPT: microtime
  - os: linux
    node_js: 8.1.3
    TEST_SCRIPT: coffeescript
  - os: linux
    node_js: 8.1.3
    TEST_SCRIPT: microtime

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - squashfs-tools
      - gcc-4.9
      - g++-4.9

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -rf /usr/local/Cellar/openssl/ && brew install squashfs openssl; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

before_script:
  - rvm install ruby-2.4.0
  - rvm use ruby-2.4.0
  - python --version
  - mksquashfs -version
  - ruby --version
  - node --version
  - npm --version

script:
  - rm -rf /tmp/nodec_tests_tmpdir && mkdir /tmp/nodec_tests_tmpdir
  - NODEC_TESTS_TMPDIR=/tmp/nodec_tests_tmpdir ruby tests/$TEST_SCRIPT || exit $?
